#!/home/a/anaconda3/bin/python

import sys

from redeal import dds
from redeal.redeal import Deal
from redeal.global_defs import Strain, Seat, Suit, Rank

#predeal = dict(N='KQJ763 95 AT92 3', E='T85 K843 7543 82', S='A942 AQT7 J AK96', W='- J62 KQ86 QJT754')

cards = sys.argv[1]
tricks = [[0,0,0], [0,0,0]]

print (cards)

predeal = {}

hands = cards.split(':')
if cards[1] == ':':
  hands = cards[2:].split()

for s in range(4):
  hand = hands[s]
  h = hand.split('.')
  pbn_h = []
  for c in h:
    if c == '':
      pbn_h.append('-')
    else:
      pbn_h.append(c)
  predeal[Seat(s)] = ' '.join(pbn_h)

print(predeal)

dealer = Deal.prepare(predeal)
deal1 = dealer(accept_func=lambda d: True)


target = -1
sol = 2
mode = 1
tricks = dict(N=[0, '', ''], E=[0, '', ''], S=[0, '', ''], W=[0, '', ''])

for leader in range(4):
  for strain in [4,0,1,2,3]:
    #print(Strain(strain), 'SHCDN'[strain], 'NESW'[leader], Seat(leader))
    # strain is CDHSN, dds is SHCDN
    s = strain
    if strain < 4:
      s = 3 - strain
    r = dds._solve_board(deal1, Strain(s), Seat(leader), target, sol, mode)
    suit = 'SHDC'[r.suit[0]]
    rank = Rank(r.rank[0])
    score = 13 - r.score[0]
    declarer = 'WNES'[leader]
    strain = 'SHDCN'[strain]
    if score > tricks[declarer][0]:
      tricks[declarer] = [score, strain, f'{suit}{rank}']
    # print ('result:', declarer, strain, f'{suit}{rank}', score)

print(tricks)

def print_future_tricks(r):
  res = dict(nodes=[], rank=[],suit=[], score=[],cards=[],equals=[])
  res['nodes'] = r.nodes
  res['cards'] = r.cards
  for i in range(13):
    res['score'].append(r.score[i])
    res['rank'].append(r.rank[i])
    res['suit'].append(r.suit[i])
  print(res)